numero1 = 4
numero2 = 6
print(numero1 + numero2)
print(numero1 * numero2)
print(numero1 - numero2)
print(numero1 / numero2)
print(numero1 // numero2)
print(numero1 % numero2)
print(numero1 ** numero2)